trigger:
- none

pr: none
pool: 
  name: demo
  demands:
  - agent.name -equals demo

stages:
- stage: MavenBuild
  displayName: MavenBuild
  jobs:    
  - job: MavenBuild
    displayName: MavenBuild
    steps:
    - task: Maven@4
      inputs:
        azureSubscription: 'Azure DevOps Service Connection'
        mavenPomFile: 'pom.xml'
        goals: 'clean install'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
- stage: MySQLDeployment
  displayName: MySQLDeployment
  dependsOn: MavenBuild
  jobs:
  - deployment: MySQLDeployment
    displayName: MySQLDeployment
    environment: "prod"
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none
          - task: KubernetesManifest@1
            inputs:
              action: 'deploy'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'Azure DevOps Service Connection'
              azureResourceGroup: 'bankappprod-rg'
              kubernetesCluster: 'bankappprod-cluster'
              namespace: 'mysql'
              manifests: 'mysql/*'
